### ISSUE TITLE
Cannot read property 'scannedAt' of undefined

### ISSUE THREAD

**Issue by michel-thomas** [hobbyquaker/check_nextcloud#3]
Hi,
I used this a week ago, and seems working fine.
But today I have this result every time:

```
/usr/local/lib/node_modules/check_nextcloud/index.js:101
    let date = result.scannedAt.date.replace(/\.[0-9]{6}$/, '');
                      ^

TypeError: Cannot read property 'scannedAt' of undefined
    at outputResult (/usr/local/lib/node_modules/check_nextcloud/index.js:101:23)
    at /usr/local/lib/node_modules/check_nextcloud/index.js:172:17
    at Request._callback (/usr/local/lib/node_modules/check_nextcloud/index.js:96:9)
    at Request.self.callback (/usr/local/lib/node_modules/check_nextcloud/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/check_nextcloud/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/check_nextcloud/node_modules/request/request.js:1083:12)
```

I tried to install it with `git clone`, and then with `npm install`. Result is the same for both.

My env is up to date Debian Stretch, nodejs version 8.11.1.

Can be from Stretch 9.7 release?

Thanks for helping

**Comment by guidtz** [comment]
@esprit-libre have you found a solution ? we have the same problem

**Comment by michel-thomas** [comment]
nope. and I haven't search more than that. sorry

**Comment by smstern** [comment]
I have the impression, that the failure will disappear as soon https://scan.nextcloud.com is working for you.

**Comment by eigenphase** [comment]
Hi everyone,

I just installed check_nextcloud 5 days ago. It worked out of the box ... for two days.
From then on I got exactly the same error message above.

Initially I used the nodejs 10 from Debian buster. I tried then installing directly v13 from the official nodejs repository in the hope the error will be gone but it's still there.

I also thought maybe there is an issue on the server end. However, manually running https://scan.nextcloud.com/ in a browser works well as expected.

It's so ODD that it worked well for two days and then suddenly stopped working ...

Any help is highly appreciated.

**Comment by eigenphase** [comment]
JFYI, I debugged this a bit by modifying:

```
function getUUID(url, cb) {
    request({
        method: 'POST',
        url: 'https://scan.nextcloud.com/api/queue',
        qs: {
            url: url
        },
        headers: {
            'Content-type': 'application/x-www-form-urlencoded',
            'X-CSRF': 'true'
        },
        json: true
    }, function (err, res, body) {
console.log("getUUID Callback");
console.log(err);
console.log(res);
console.log(body);
        if (!err && body && body.uuid) {
            cb(null, body.uuid)
        } else {
            cb(err);
        }
    });
}
```




```
  [...]
  caseless: Caseless {
    dict: {
      date: 'Mon, 23 Mar 2020 17:32:39 GMT',
      server: 'Apache/2.4.29 (Ubuntu)',
      'strict-transport-security': 'max-age=15768000; includeSubDomains; preload',
      'content-security-policy': "default-src 'none';",
      'x-frame-options': 'none',
      'x-xss-protection': '1; mode=block',
      'x-content-type-options': 'nosniff',
      'content-length': '28',
      connection: 'close',
      'content-type': 'application/json;charset=utf-8'
    }
  },
  **body: 'Too many instances queued.',**
  [Symbol(kCapture)]: false
  [...]
```

Looks like my nagios did too many requests.
I then tried with a browser and indeed get

 **Scan failed!  The scan for the specified domain failed. Either no Nextcloud or ownCloud can be found there or you tried to scan too many servers.** 

but works from a different IP. Seems they have banned my IP.

Hope I get unbanned after some time and then will have to increase the check rate in nagios.
